version: '3.3'

services:

  studer2influx:
    build: studerlogger
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${STUDERLOGGER_XCOMLAN_LISTEN_PORT}:${STUDERLOGGER_XCOMLAN_LISTEN_PORT}"
