version: '3.8'

volumes:
  influxdb_volume:
  grafana_volume:

services:

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - ${DATADIR}/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=grafana

  grafana:
    image: grafana/grafana:9.3.6
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${DATADIR}/grafana:/var/lib/grafana
    user: "0"

  studer2influx:
    build: studer2influx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${STUDER2INFLUX_XCOMLAN_LISTEN_PORT}:${STUDER2INFLUX_XCOMLAN_LISTEN_PORT}"
