{
 "title": "Studer monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Battery SOC",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery SOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "select": [
      [
       { "params": [ "BATT_SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Battery Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "select": [
      [
       { "params": [ "BATT_TEMP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Battery Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "select": [
      [
       { "params": [ "BATT_CURRENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Battery Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "select": [
      [
       { "params": [ "BATT_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "XTM1 Power OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "select": [
      [
       { "params": [ "AC_POWER_OUT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "XT-1" }
     ]
    },
    {
     "alias": "XTM2 Power OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "select": [
      [
       { "params": [ "AC_POWER_OUT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "XT-2" }
     ]
    },
    { "expression": "$G + $H", "type": "math" },
    { "expression": "$G + $H - ($D + $E)", "type": "math" }
   ]
  },
  {
   "title": "Invertors - power out",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "XTM1 AC power OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_POWER_OUT" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-1" }
     ]
    },
    {
     "alias": "XTM2 AC power OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_POWER_OUT" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-1" }
     ]
    },
    {
     "alias": "XTM1 AC current OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT mean(\"AC_CURRENT_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = '${deviceName}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_CURRENT_OUT" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-1" }
     ]
    },
    {
     "alias": "XTM2 AC current OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT mean(\"AC_CURRENT_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = '${deviceName}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_CURRENT_OUT" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-2" }
     ]
    }
   ]
  },
  {
   "title": "Invertors - power in",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "XTM1 AC power IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT mean(\"AC_CURRENT_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = '${deviceName}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_POWER_IN" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-1" }
     ]
    },
    {
     "alias": "XTM2 AC power IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT mean(\"AC_CURRENT_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = '${deviceName}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_POWER_IN" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-2" }
     ]
    },
    {
     "alias": "XTM1 AC current IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT mean(\"AC_CURRENT_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = '${deviceName}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_CURRENT_IN" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-1" }
     ]
    },
    {
     "alias": "XTM2 AC current IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT mean(\"AC_CURRENT_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = '${deviceName}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_CURRENT_IN" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "XT-2" }
     ]
    }
   ]
  },
  {
   "title": "MPPT",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "VT1 PV power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "VT-1" }
     ]
    },
    {
     "alias": "VT2 PV power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PV_POWER" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "VT-2" }
     ]
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Battery SOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "BATT_SOC" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Battery current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "BATT_CURRENT" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Battery temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "BATT_TEMP" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "SELECT distinct(\"AC_POWER_OUT\") FROM \"solar_data\" WHERE (\"deviceName\" = 'XT-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "BATT_VOLTAGE" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Power total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "PV daily statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "alias": "Daily VT-1",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "select max(PV_ENERGY_PREV_DAY) from solar_data where deviceName='VT-1' and time > now() - 7d group by time(1d)\n",
     "select": [
      [
       { "params": [ "PV_ENERGY_TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "VT-1" }
     ]
    },
    {
     "alias": "Daily VT-2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "select max(PV_ENERGY_PREV_DAY) from solar_data where deviceName='VT-2' and time > now() - 7d group by time(1d)\n",
     "select": [
      [
       { "params": [ "PV_ENERGY_TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "VT-1" }
     ]
    }
   ]
  },
  {
   "title": "Hourly statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "alias": "Hourly VT-1",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "select difference(max(PV_ENERGY_TOTAL)) from solar_data where deviceName='VT-1' and  $timeFilter group by time(1h)\n",
     "select": [
      [
       { "params": [ "PV_ENERGY_TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "VT-1" }
     ]
    },
    {
     "alias": "Hourly VT-2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_data",
     "query": "select difference(max(PV_ENERGY_TOTAL)) from solar_data where deviceName='VT-2' and  $timeFilter group by time(1h)\n",
     "select": [
      [
       { "params": [ "PV_ENERGY_TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=", "value": "VT-1" }
     ]
    }
   ]
  }
 ]
}