version: '3.3'

volumes:
  influxdb_volume:
  grafana_volume:

services:

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - ${DATADIR}/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=grafana

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${DATADIR}/grafana:/var/lib/grafana
    user: "0"

  mosquitto:
    build: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"


  studerlogger:
    build: studerlogger
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${XCOMLAN_LISTEN_PORT}:${XCOMLAN_LISTEN_PORT}"
